baseURL = 'https://1v0.dev/'
languageCode = 'en-us'
title = '1\/0'

theme = "hello-friend"

[params]
# OS theme is default when not provided, but you can force it to "light" or "dark"
defaultTheme = "light"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 4

# Show reading time in minutes for posts
showReadingTime = true

[params.mermaid]
theme = "neutral"
align = "center"

# Show full page content in RSS feed items
#(default is Description or Summary metadata in the front matter)
# rssFullText = true

[languages]
[languages.en]
title = "1v0.dev"
subtitle = ""
keywords = ""

[languages.en.params.logo]
logoText = "1v0.dev"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "archive"
name = "All Posts"
url = "/archive"
weight = 50